routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//ruta de recursos GET POST PUT DELETE
Route::resource('/registros',App\Http\Controllers\RegistrosController::class);
Route::resource('/tipos',App\Http\Controllers\TiposController::class);

//ruta normal 
//Route::get('/registros',[App\Http\Controllers\RegistrosController::class,'index']);

app/Models/Registros.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Registros extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['autor','titulo','descripcion','editorial','fecha','ventas','id_tipo'];
}

app/Models/Tipos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tipos extends Model
{
    use HasFactory;
    protected $fillable = ['tipo'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/RegistrosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tipos;
use App\Models\Registros;
use Illuminate\Http\Request;

class RegistrosController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $registros = Registros::select('registros.id','autor','titulo','descripcion','editorial','fecha','ventas','id_tipo','tipo')
        ->join('tipos','tipos.id','=','registros.id_tipo')->get();
        $tipos = Tipos::all();
        return view('librovista',compact('registros'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $tipos = Tipos::all();

        return view('crear', compact('tipos'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'autor'=> 'required',
            'titulo'=> 'required',
            'descripcion'=> 'required',
            'editorial'=> 'required',
            'fecha' => 'required',
            'ventas' => 'required|numeric',
            'id_tipo' => 'required',

        ]);
        $registros = new Registros($request->input());
        $registros-> save();
        return redirect()->route('registros.index')->with('success','Acción realizada exitosamente');
    }

    /**
     * Display the specified resource.
     */
    public function show(Registros $registros)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $registros= Registros ::find($id);
        $tipos = Tipos::all();
        return view('editar',compact('registros', 'tipos'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'autor'=> 'required',
            'titulo'=> 'required',
            'descripcion'=> 'required',
            'editorial'=> 'required',
            'fecha' => 'required',
            'ventas' => 'required|numeric',
            'id_tipo' => 'required',

        ]);
        
        $registro = Registros::find($id);
        $registro-> update($request->input());
        return redirect()->route('registros.index')->with('success',' Registro Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $registros = Registros::find($id);
        $registros->delete();
        return redirect()->route('registros.index')->with('success','Registro eliminado');
    }
}

app/Http/Controllers/TiposController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tipos;
use Illuminate\Http\Request;

class TiposController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tipos = Tipos::all();
        return view('tipos', compact('tipos'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('crear');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'tipo'=> 'required'
        ]);
        $tipos = new Tipos($request->input());
        $tipos-> saveOrFail();
        return redirect()->route('tipos.index')->with('success','Género de libro guardado');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $tipo= Tipos::find($id);
            return view('editarTipo',compact('tipo'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'tipo'=> 'required'
        ]);
        $tipos = Tipos::find($id);
        $tipos-> update($request->input());
        return redirect()->route('tipos.index')->with('success','Género de libro Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $tipos = Tipos::find($id);
        $tipos->delete();
        return redirect()->route('tipos.index')->with('success','GÉNERO DE LIBRO ELIMINADO');
    }
}

resources/views/crear.blade.php
@extends('plantilla')
@extends('formulario')


@section('action')
    action="{{ route('registros.store') }}"
@endsection

resources/views/editar.blade.php
@extends('plantilla')
@extends('formulario')

@section('action')
    action="{{ route('registros.update',$registros->id) }}"
@endsection
@section ('metodo')
    @method('PUT')
@endsection

resources/views/editarTipo.blade.php
@extends('plantilla')
@section('form')
Creando...
@endsection
@section('principal')
<div class="row mt-6">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header bg-dark text-white">Género de libro</div>
            <div class="card-body">
                <form method="POST"  action="{{ route('tipos.update',$tipo->id) }}" >
                    @csrf 
                    @method('PUT')
                    <div class="input-group mb-3">
                        <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                        <input name="tipo" type="text" class="form-control" placeholder="GÉNERO DE LIBRO" @isset($tipo)
                            value = "{{$tipo->tipo}}" 
                        @endisset>
                      </div>
                     <div class="card-footer">
                        <div class="row-md-3 offset-md-3">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="fa-solid fa-ban"></i> Cancelar</button>
                        <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> GUARDAR</button>    
                        </div>
                    </div>   
            </div>
        </div>

    </div>
    
</div>  
@endsection

resources/views/formulario.blade.php
@section('principal')
@if($errors->any())
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="alert alert-danger">
        <ul>
          @foreach($errors->all() as $e)
            <li>{{$e}} </li>
          @endforeach
        </ul>
      </div>
    </div>
  </div>
@endif

<div class="row">
    <div class="col  mt-3">
        <div class="card">
            <div class="card-header"><h3>REGISTRO DE LIBRO<h3></div>
            <div class="card-body">
                    <form method="POST" @yield('action')>
                        @csrf 
                        @yield('metodo')
                        <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-user"></i></span>
                            <input name="autor" type="text" class="form-control" placeholder="autor" @isset($registros)
                                value = "{{$registros->autor}}"
                            @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book "></i></span>
                            <input name="titulo" type="text" class="form-control" placeholder="titulo" @isset($registros)
                            value = "{{$registros->titulo}}"
                        @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                            <input name="descripcion" type="text" class="form-control" placeholder="descripcion" @isset($registros)
                            value = "{{$registros->descripcion}}"
                        @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                            <input name="editorial" type="text" class="form-control" placeholder="editorial" @isset($registros)
                            value = "{{$registros->editorial}}"
                        @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                            <input name="fecha" type="date" class="form-control" placeholder="fecha" @isset($registros)
                            value = "{{$registros->fecha}}"
                        @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                            <input name="ventas" type="number" class="form-control" placeholder="ventas" @isset($registros)
                            value = "{{$registros->ventas}}"
                        @endisset>
                          </div>
                          <div class="input-group mb-3">
                            <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                            <select name="id_tipo" class="form-select" required>
                                    @foreach($tipos as $row)
                                   
                                    <option value="{{$row->id}}">{{$row->tipo}}</option>
                                     
                                    @endforeach
                            </select>
                          </div>
                          
                          <button class="btn btn-success">guardar</button>
                    </form>
            </div>
        </div>
    </div>
</div>
@vite('resources/js/listado.js')
@endsection

resources/views/librovista.blade.php
@extends('plantilla')
@section('titulo')
-Registros
@endsection

@section('principal')

@if($mensaje = Session::get('success'))
    <div class="row" id="divok">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-success">
                {{ $mensaje }}
            </div>
        </div>
    </div>
@endif
<div class="row">
    <div class="col-12">
        <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>AUTOR</th>
                                <th>TITULO DEL LIBRO</th>
                                <th>DESCRIPCIÓN</th>
                                <th>EDITORIAL</th>
                                <th>FECHA</th>
                                <th>VENTAS</th>
                                <th>TIPOS</th>
                            
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($registros as $i => $row)
                                <tr>
                                    <td>{{($i+1)}}</td>
                                    <td>{{$row->autor}}</td>
                                    <td>{{$row->titulo}}</td>
                                    <td>{{$row->descripcion}}</td>
                                    <td>{{$row->editorial}}</td>
                                    <td>{{$row->fecha}}</td>
                                    <td>{{$row->ventas}}</td>
                                    <td>{{$row->tipo}}</td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('registros.edit',$row->id)}}"> <i class="fa-solid fa-pencil"></i> </a>
                                    </td>
                                    <td>

                                        <form method="POST" id="frm_{{$row->id}}" action="{{route('registros.destroy', $row->id)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button onclick="datos('{{$row->id}}','{{$row->autor}}')" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminarTipo"><i class="fa-solid fa-trash-can" style="color: #f0f2f4;"></i></button>
                                        </form>
                                        
                                    </td>

                                    
                                    
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="modal" tabindex="-1" id="modalEliminarTipo">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title"><i class="fa-solid fa-warning"></i> Atención!!!</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <p>¿Seguro de elimiar el registro?</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="fa-solid fa-ban"></i> Cancelar</button>
                              <button id="btnEliminarR" type="button" class="btn btn-success">Si, eliminar</button>
                            </div>
                          </div>
                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>
</div>
</div>

@endsection

@section('js')
    @vite('resources/js/listado.js')
@endsection

resources/views/plantilla.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>LIBROS :D</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">L I B R O S</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{{ route('tipos.index')}}">Tipos</a>
              <a class="nav-link" href="{{ route('registros.index')}}">Registros</a>
                <a class="nav-link" href="{{ route('registros.create')}}">Crear registros</a>
            </div>
          </div>
        </div>
      </nav>
      <div class="container mt-3">
        @yield('principal')
      </div>
</body>
@yield('js')
</html>

resources/views/tipos.blade.php
@extends('plantilla')
@section('titulo')
-Registros
@endsection

@section('principal')

@if($mensaje = Session::get('success'))
    <div class="row" id="divok">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-success">
                {{ $mensaje }}
            </div>
        </div>
    </div>
@endif

<div class="row mt-3">
    <div class="col-md-4 offset-md-4">
        <div class="d-grid mx-auto">
        <button class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#modalTipos">
            <i class="fa-solid fa-circle-plus"></i>
           AÑADIR </button>
    </div>
</div>
</div>

<div class="row mt-3">
    <div class="col-12">
        <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>GÉNERO DE LIBRO</th>
                                <th>EDITAR</th>
                                <th>ELIMINAR</th>                                
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($tipos as $i => $row)
                                <tr>
                                    <td>{{($i+1)}}</td>
                                    <td>{{$row->tipo}}</td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('tipos.edit',$row->id)}}"> <i class="fa-solid fa-pencil"></i> </a>
                                    </td>
                                     <td>   
                                        <form method="POST" id="frm_{{$row->id}}" action="{{route('tipos.destroy', $row->id)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button  onclick="datos('{{$row->id}}','{{$row->tipo}}')" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminar"><i class="fa-solid fa-trash-can" style="color: #f0f2f4;"></i></button>
                                        </form>
                                    </td>
                                    </td>

                                    
                                    
                                </tr>
                            @endforeach
                        </tbody>
                    </div>
        </div>
</div>

@if($errors->any())
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="alert alert-danger">
        <ul>
          @foreach($errors->all() as $e)
            <li>{{$e}} </li>
          @endforeach
        </ul>
      </div>
    </div>
  </div>
@endif

<div class="modal" tabindex="-1" id="modalTipos">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">GÉNERO DE LIBRO</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST">
                @csrf 
                @yield('metodo')
                <div class="input-group mb-3">
                    <span class="input-group-text" ><i class="fa-solid fa-book"></i></span>
                    <input name="tipo" type="text" class="form-control" placeholder="GÉNERO DE LIBRO" @isset($tipo)
                        value = "{{$tipos->tipo}}"
                    @endisset>
                  </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="fa-solid fa-ban"></i> Cancelar</button>
          <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> GUARDAR</button>
        </div>
      </div>
    </div>
  </div>



  <div class="modal" tabindex="-1" id="modalEliminar">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><i class="fa-solid fa-warning"></i> D A G E R ! ! !</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>¿Seguro de elimiar el género del libro ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="fa-solid fa-ban"></i> Cancelar</button>
          <button id="btnEliminar" type="button" class="btn btn-success">Si, eliminar</button>
        </div>
      </div>
    </div>
  </div>
@vite('resources/js/listado.js')
@endsection